import Project.HostCounter.Program
import Project.HostCounter.Host

/-!
# Specification for `host_counter`

The exported `step()` calls `host_get`; if the returned counter is
strictly less than `10`, it calls `host_inc` to bump it. We claim
that this preserves the invariant `counter ≤ 10`: if it held before
the call, it holds after — regardless of which `HostEnv`
implementation is supplied, as long as it satisfies `counterSpec`.

The spec is stated as `PartiallyMeets`: every successful run lands in
a state where the invariant holds. Termination is not part of the
claim, though for this branch-only program it would hold too.
-/

namespace Project.HostCounter.Spec

open Wasm
open Project.HostCounter.Host

/-- The program-level invariant `step` preserves: the host counter is
at most `10`. This is a property of the *program* (its guarded
increment never lets the counter exceed `10`), not of the host —
the host on its own permits arbitrary counter values. -/
def CounterInv (st : Store CounterState) : Prop :=
  st.host.counter ≤ 10

/-- The unified function index of the exported `step` wrapper in the
decoded module. Imports occupy the low end of the index space
(`host_inc = 0`, `host_get = 1`), so the in-module functions start at
`2`. The exact index depends on how `rustc` lays out helpers and is
filled in once `Program.lean` is generated by `verifier check`. -/
def stepIdx : Nat := 2

/-- `step` preserves the counter-invariant.

Stated as partial correctness over every `HostEnv` satisfying
`counterSpec`. The proof will reason only via the contracts, never
the concrete `incHost` / `getHost`. -/
@[spec_of "rust-exported" "host_counter::step"]
def StepPreservesInv : Prop :=
  ∀ (env : HostEnv CounterState) (initial : Store CounterState),
    env.Satisfies «module» counterSpec →
    CounterInv initial →
    PartiallyMeets env «module» stepIdx initial []
      (fun st _ => CounterInv st)

@[proves Project.HostCounter.Spec.StepPreservesInv]
theorem step_preserves_inv : StepPreservesInv := by
  intro env initial hSat hInv
  apply TerminatesWith.toPartiallyMeets
  apply TerminatesWith.of_wp_entry_for
      (f := ⟨[], [], func0, []⟩) rfl
  unfold func0
  simp only [Function.toLocals, Function.numParams, List.length_nil,
    List.take, List.reverse_nil, List.map]
  apply wp_block_cons
  obtain ⟨hfG, cG, hEnvG, hCG, hInvG⟩ := hSat 0 (by decide)
  obtain ⟨hfI, cI, hEnvI, hCI, hInvI⟩ := hSat 1 (by decide)
  have hCGid : counterSpec.contracts[0]? = some getContract := rfl
  rw [hCGid] at hCG; injection hCG with hCG'; subst hCG'
  have hCIid : counterSpec.contracts[1]? = some incContract := rfl
  rw [hCIid] at hCI; injection hCI with hCI'; subst hCI'
  refine wp_call_host_cons
    (imp := ⟨"env", "host_get", [], [.i32]⟩) (hf := hfG)
    rfl hEnvG ?_ ?_
  · intro vs st' hRet
    simp at hRet
    have hG := hInvG initial []
    unfold getContract at hG
    obtain ⟨_, hRes⟩ := hG
    rw [hRet] at hRes
    injection hRes with hvs hst
    subst vs; subst st'
    simp [wp_simp]
    by_cases hgt : UInt32.ofNat initial.host.counter > (9 : UInt32)
    · simp [hgt]
      exact hInv
    · simp [hgt]
      refine wp_call_host_cons
        (imp := ⟨"env", "host_inc", [], []⟩) (hf := hfI)
        rfl hEnvI ?_ ?_
      · intro vs2 st2 hRet2
        simp at hRet2
        have hI := hInvI initial []
        unfold incContract at hI
        obtain ⟨_, hRes2⟩ := hI
        rw [hRet2] at hRes2
        injection hRes2 with hvs2 hst2
        subst vs2; subst st2
        simp [wp_simp]
        unfold CounterInv
        unfold CounterInv at hInv
        dsimp only []
        have hle9 : initial.host.counter ≤ 9 := by
          by_contra h
          push Not at h
          have h10 : initial.host.counter = 10 := by omega
          rw [h10] at hgt
          exact hgt (by decide)
        omega
      · intro st2 msg2 hTrap2
        simp at hTrap2
        have hI := hInvI initial []
        unfold incContract at hI
        obtain ⟨_, hRes2⟩ := hI
        rw [hTrap2] at hRes2
        cases hRes2
  · intro st' msg hTrap
    simp at hTrap
    have hG := hInvG initial []
    unfold getContract at hG
    obtain ⟨_, hRes⟩ := hG
    rw [hTrap] at hRes
    cases hRes

end Project.HostCounter.Spec
